spring:
  profiles:
    active: local
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: foodie_road_store
      username: root
      password: rot@123
      authentication-database: admin
      auto-index-creation: true

  application:
    name: foodieRoad